CREATE TABLE books
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    author         VARCHAR(255)                            NOT NULL,
    published_year INTEGER,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE indicator
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    green_threshold  DOUBLE PRECISION,
    yellow_threshold DOUBLE PRECISION,
    red_threshold    DOUBLE PRECISION,
    status           VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    CONSTRAINT pk_indicator PRIMARY KEY (id)
);

CREATE TABLE indicator_value
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    indicator_id BIGINT          NOT NULL,
    value        DOUBLE PRECISION NOT NULL,
    recorded_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_indicator_value PRIMARY KEY (id),
    CONSTRAINT fk_indicator_value_indicator FOREIGN KEY (indicator_id) REFERENCES indicator (id) ON DELETE CASCADE
);