CREATE TABLE rodiklis
(
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pavadinimas   VARCHAR(255) NOT NULL,
    aprasymas     TEXT,
    riba_zalia    DOUBLE PRECISION,
    riba_geltona  DOUBLE PRECISION,
    riba_raudona  DOUBLE PRECISION
);

CREATE TABLE books
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    author         VARCHAR(255)                            NOT NULL,
    published_year INTEGER,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE indicator
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    green_threshold  DOUBLE PRECISION,
    yellow_threshold DOUBLE PRECISION,
    red_threshold    DOUBLE PRECISION,
    CONSTRAINT pk_indicator PRIMARY KEY (id)
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    author         VARCHAR(255) NOT NULL,
    published_year INT
);