CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(100)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL UNIQUE,
    password       VARCHAR(255)                            NOT NULL,
    role           VARCHAR(20)                             NOT NULL,
    created_at     TIMESTAMPTZ                             NOT NULL DEFAULT NOW(),
    last_login     TIMESTAMPTZ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT valid_roles CHECK (role IN ('ANALYST', 'DIRECTOR', 'ADMIN'))
);

/*
Password is Bcrypt. Generate using https://bcrypt-generator.com/ (set Rounds (Cost Factor): 10)
$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G = 1234
*/

INSERT INTO users (name, email, password, role)
VALUES
('Jonas Kazlauskas', 'an@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'ANALYST'),
('Mantas Petraitis', 'di@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'DIRECTOR'),
('Admin User', 'ad@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'ADMIN');