CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255)                            NOT NULL UNIQUE,
    password       VARCHAR(255)                            NOT NULL,
    role           VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT valid_roles CHECK (role IN ('ANALYST', 'DIRECTOR', 'ADMIN'))
);

/*
Password is Bcrypt. Generate using https://bcrypt-generator.com/ (set Rounds (Cost Factor): 10)
$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G = 1234
*/

INSERT INTO users (email, password, role)
VALUES
('an@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'ANALYST'),
('di@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'DIRECTOR'),
('ad@gmail.com', '$2a$10$fAxREMce7IPoHNYlT822Du9LYGiOmHxfLBlWlUH5w11M/PeerpA1G', 'ADMIN');