ALTER TABLE indicator
    DROP COLUMN green_threshold,
    DROP COLUMN yellow_threshold,
    DROP COLUMN red_threshold;

CREATE TABLE indicator_thresholds
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    indicator_id     BIGINT NOT NULL,
    green_threshold  DOUBLE PRECISION,
    yellow_threshold DOUBLE PRECISION,
    red_threshold    DOUBLE PRECISION,
    recorded_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_indicator_threshold PRIMARY KEY (id),
    CONSTRAINT fk_indicator_threshold_indicator FOREIGN KEY (indicator_id) REFERENCES indicator (id) ON DELETE CASCADE
);

INSERT INTO indicator_thresholds (indicator_id, green_threshold, yellow_threshold, red_threshold, recorded_at)
    SELECT id, 1.5, 1.0, 0.5, CURRENT_TIMESTAMP FROM indicator WHERE name = 'Liquidity Ratio';

INSERT INTO indicator_thresholds (indicator_id, green_threshold, yellow_threshold, red_threshold, recorded_at)
    SELECT id, 30.0, 50.0, 70.0, CURRENT_TIMESTAMP FROM indicator WHERE name = 'Debt Ratio';