CREATE TABLE indicator
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    green_threshold  DOUBLE PRECISION,
    yellow_threshold DOUBLE PRECISION,
    red_threshold    DOUBLE PRECISION,
    CONSTRAINT pk_indicator PRIMARY KEY (id)
);